Feature/add param for pinch drag
google/marzipano pull request #373
Opened 2021-01-21 16:25 UTC by jean9696

Hello there, 

We want to integrate a marzipano view in a scrollable page the current state of the library does not behave well in this case, when you have the marzipano view fullscreen in mobile you can't scroll anymore because it moves inside marzipano view instead of scrolling the page. So we would like to allow our user to move marzipano view with 2 fingers. 
I made a naïve implementation but it seems to work fine with the following configuration:
```js
  // Viewer options.
    var viewerOpts = {
      controls: {
        mouseViewMode: data.settings.mouseViewMode,
        dragMode: 'pinch'
      }
    };

    // Initialize viewer.
    var viewer = new Marzipano.Viewer(panoElement, viewerOpts);
```

Thank you !

related to https://github.com/google/marzipano/issues/367

(if it gets merge I will update my PR with typescript definition https://github.com/google/marzipano/pull/371)

2021-02-28 00:36 UTC, tjgq requested changes
Looks good, just a couple of minor issues. (Sorry for the delay!)

2021-02-28 00:36 UTC, tjgq commented on src/controls/Drag.js
> +  if (!['pan', 'pinch'].includes(this._opts.hammerEvent)) {
Please use `x != 'pan' && x != 'pinch'` here - `Array#includes` doesn't exist on IE11, which in principle we still support.

2021-02-28 00:36 UTC, tjgq commented on src/controls/registerDefaultControls.js
> +    default:
Write an error check in the `default` case, like we do for `opt.mouseViewMode` below.

2021-03-06 10:06 UTC, jean9696 commented
@tjgq I fixed it 👍

2021-03-18 02:46 UTC, merged